experiment:
  name: "hyperparam_sensitivity"
  description: "FedDive momentum sensitivity on MNIST non-IID Î±=0.1"
  seed: 42
  runs: 1

dataset:
  name: "mnist"
  batch_size: 32
  partition: "dirichlet"
  alpha: 0.1

model:
  name: "simple_cnn"
  in_channels: 1
  num_classes: 10

federated:
  num_clients: 10
  clients_per_round: 5
  num_rounds: 15
  local_epochs: 2
  learning_rate: 0.01

feddive:
  epsilon: 1e-8
  temperature: 1.0
  normalize_distances: true
  momentum_values: [0.5, 0.7, 0.9, 0.95]