# Non-IID experiment configuration
experiment:
  name: "non_iid_performance"
  description: "Testing performance under increasing data heterogeneity"
  seed: 42
  runs: 1  # Number of independent runs
  
dataset:
  name: "mnist"
  batch_size: 32
  partition: "dirichlet"
  alpha_values: [10.0, 1.0, 0.5, 0.1]  # From nearly IID to highly skewed
  
model:
  name: "simple_cnn"
  in_channels: 1
  num_classes: 10
  
federated:
  num_clients: 10
  clients_per_round: 5
  num_rounds: 15
  local_epochs: 2
  learning_rate: 0.01
  
aggregators:
  - name: "fedavg"
  - name: "fedprox"
    mu: 0.01
  - name: "feddive"
    momentum: 0.9
    temperature: 1.0
    epsilon: 1e-8
    normalize_distances: true