experiment:
  name: "stability_analysis"
  description: "Stability metrics for FedDive (fixed/dynamic) and FedDive-R on MNIST non-IID Î±=0.1"
  seed: 42
  runs: 1

dataset:
  name: "mnist"
  batch_size: 32
  partition: "dirichlet"
  alpha: 0.1

model:
  name: "simple_cnn"
  in_channels: 1
  num_classes: 10

federated:
  num_clients: 10
  clients_per_round: 5
  num_rounds: 15
  local_epochs: 2
  learning_rate: 0.01

aggregators:
  - name: "feddive"
    momentum: 0.9
    temperature: 1.0
    epsilon: 1e-8
    normalize_distances: true
  - name: "feddive"
    is_dynamic: true
    momentum: 0.9
    epsilon: 1e-8
    normalize_distances: true
    temp_schedule: "cosine"
    initial_temp: 5.0
    final_temp: 0.5
  - name: "feddiver"
    momentum: 0.9
    temperature: 1.0
    epsilon: 1e-8
    normalize_distances: true